version: '2'

services:
 pg-master:
   build: '.'
   image: 'danieldent/postgres-replication'
   restart: 'always'
   environment:
     POSTGRES_USER: 'postgres'
     POSTGRES_PASSWORD: 'postgres'
     PGDATA: '/var/lib/postgresql/data/pgdata'
   volumes:
    - '/var/lib/postgresql/data'
    - ./archive:/opt/
   ports:
    - 15432:5432

 pg-slave:
   build: '.'
   image: 'danieldent/postgres-replication'
   restart: 'always'
   environment:
     POSTGRES_USER: 'postgres'
     POSTGRES_PASSWORD: 'postgres'
     PGDATA: '/var/lib/postgresql/data/pgdata'
     REPLICATE_FROM: 'pg-master'
   volumes:
    - '/var/lib/postgresql/data'
   expose:
    - '5432'
   links:
    - 'pg-master'

 minio1:
  image: minio/minio
  volumes:
   - V11:/export
  ports:
   - "9001:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: admin1234
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
 minio2:
  image: minio/minio
  volumes:
   - V12:/export
  ports:
   - "9002:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: admin1234
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
 minio3:
  image: minio/minio
  volumes:
   - V13:/export
  ports:
   - "9003:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: admin1234
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 
 minio4:
  image: minio/minio
  volumes:
   - V14:/export
  ports:
   - "9004:9000"
  environment:
   MINIO_ACCESS_KEY: admin
   MINIO_SECRET_KEY: admin1234
  command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export 


## By default this config uses default local driver,
## For custom volumes replace with volume driver configuration.
volumes:
  V11:
  V12:
  V13:
  V14:
